// Uses the rules generated by @nuxt/eslint for this project (Vue + TS + Nuxt
// auto-imports). Run: npm run lint
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  rules: {
    // Pages like index.vue / [id].vue are single-word by Nuxt convention.
    'vue/multi-word-component-names': 'off',
  },
})
