<script setup lang="ts">
import type { AuthStage } from '#shared/types/admin'

definePageMeta({ layout: 'auth', middleware: 'admin' })

const { t } = useI18n()
const localePath = useLocalePath()
const { request } = useAdminApi()
useHead({ title: () => t('dashboard.mfa.verifyTitle') })

const stage = ref<AuthStage>('signed_out')
const enrollment = ref<{ qrCode: string; secret: string } | null>(null)
const code = ref('')
const busy = ref(false)
const errorKey = ref('')

onMounted(async () => {
  try {
    stage.value = (await request<{ stage: AuthStage }>('/api/auth/session')).stage
    if (stage.value === 'mfa_enroll') {
      enrollment.value = await request('/api/auth/mfa/enroll', { method: 'POST' })
    }
  } catch (err) {
    errorKey.value = adminErrorKey(err)
  }
})

async function submit() {
  busy.value = true
  errorKey.value = ''
  try {
    await request('/api/auth/mfa/verify', { method: 'POST', body: { code: code.value } })
    await navigateTo(localePath('/dashboard'))
  } catch (err) {
    errorKey.value = adminErrorKey(err)
    code.value = ''
  } finally {
    busy.value = false
  }
}
</script>

<template>
  <div>
    <template v-if="stage === 'mfa_enroll'">
      <h1 class="text-lg font-heading font-bold">{{ t('dashboard.mfa.enrollTitle') }}</h1>
      <p class="text-sm text-neutral-600 mt-1">{{ t('dashboard.mfa.enrollIntro') }}</p>
      <div v-if="enrollment" class="mt-4">
        <!-- The QR is an SVG data URI generated by Supabase Auth. -->
        <img :src="enrollment.qrCode" alt="" width="180" height="180" class="mx-auto rounded-md bg-white p-2" >
        <p class="mt-3 text-xs text-neutral-600">{{ t('dashboard.mfa.secretLabel') }}</p>
        <code class="block mt-1 text-xs break-all rounded-sm bg-neutral-100 px-2 py-1.5 select-all" dir="ltr">
          {{ enrollment.secret }}
        </code>
      </div>
      <p v-else-if="!errorKey" class="mt-4 text-sm text-neutral-500">{{ t('dashboard.mfa.loading') }}</p>
    </template>
    <template v-else>
      <h1 class="text-lg font-heading font-bold">{{ t('dashboard.mfa.verifyTitle') }}</h1>
      <p class="text-sm text-neutral-600 mt-1">{{ t('dashboard.mfa.verifyIntro') }}</p>
    </template>

    <form class="mt-6 space-y-4" @submit.prevent="submit">
      <div>
        <label for="code" class="field-label">{{ t('dashboard.mfa.code') }}</label>
        <input
          id="code"
          v-model="code"
          type="text"
          inputmode="numeric"
          pattern="\d{6}"
          maxlength="6"
          required
          autocomplete="one-time-code"
          dir="ltr"
          class="field-input text-center tracking-[0.4em] text-lg"
        >
      </div>
      <p v-if="errorKey" class="text-sm text-red-700 dark:text-red-300" role="alert">{{ t(errorKey) }}</p>
      <button type="submit" class="btn-primary w-full" :disabled="busy || code.length !== 6">
        {{ t('dashboard.mfa.submit') }}
      </button>
    </form>
  </div>
</template>
